// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoxiasApp.Infrastructure.Data;

#nullable disable

namespace Voxia.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CardClickStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsHomeCard")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CardStats");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CardFavorito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CategoriaFavoritoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImagemPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaFavoritoId");

                    b.ToTable("CardsFavoritos");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CardHome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CategoriaHomeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaHomeId");

                    b.ToTable("CardsHome");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AudioUrl = "/assets/system/audio/maca.mp3",
                            CategoriaHomeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImagemUrl = "/assets/system/images/maca.png",
                            Nome = "Maçã"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AudioUrl = "/assets/system/audio/banana.mp3",
                            CategoriaHomeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImagemUrl = "/assets/system/images/banana.png",
                            Nome = "Banana"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AudioUrl = "/assets/system/audio/cachorro.mp3",
                            CategoriaHomeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ImagemUrl = "/assets/system/images/cachorro.png",
                            Nome = "Cachorro"
                        });
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CategoriaFavorito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CategoriasFavoritos");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CategoriaHome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasHome");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "Frutas"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "Animais"
                        });
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CardClickStat", b =>
                {
                    b.HasOne("Voxia.Api.Domain.Entities.User", "User")
                        .WithMany("Stats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CardFavorito", b =>
                {
                    b.HasOne("Voxia.Api.Domain.Entities.CategoriaFavorito", "Categoria")
                        .WithMany("Cards")
                        .HasForeignKey("CategoriaFavoritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CardHome", b =>
                {
                    b.HasOne("Voxia.Api.Domain.Entities.CategoriaHome", "Categoria")
                        .WithMany("Cards")
                        .HasForeignKey("CategoriaHomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CategoriaFavorito", b =>
                {
                    b.HasOne("Voxia.Api.Domain.Entities.User", "User")
                        .WithMany("CategoriasFavoritos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CategoriaFavorito", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.CategoriaHome", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Voxia.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("CategoriasFavoritos");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
